import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    paddingVertical: 48,
    paddingHorizontal: 24,
    paddingBottom: 0,
    gap: 24,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchCreateContainer: {
    flexDirection: 'column',
    gap: 16,
    alignSelf: 'stretch',
    height: 92,
  },
  createContainer: {
    alignSelf: 'stretch',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    flex: 1,
  },
  createProfileBtn_light: {
    height: 38,
    gap: 8,
    flexDirection: 'row',
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderColor: '#3DACFF',
  },
  createProfileBtn_dark: {
    height: 38,
    gap: 8,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  createText_light: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.25,
    textTransform: 'capitalize',
    color: '#3DACFF',
  },
  createText_dark: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.25,
    textTransform: 'capitalize',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  errorText_light: {
    padding: 10,
    color: '#212121',
  },
  errorText_dark: {
    padding: 10,
    color: '#ffffff',
  },
});
